# general configuration
url: https://ucla-labx.github.io
baseurl: ''

# compass configuration
compass:
  # an avatar or logo (optional)
  # author will appear under the avatar (optional)
  author: "UCLA LABX"
  # tagline will appear under the title (optional)
  tagline: 'ML research & engineering
    <span class="fa fa-github fa-lg main-list-item-icon"></span>
    <a href="https://github.com/ucla-labx">GitHub</a>'
  # if include_content is true, the contents of the cotent.html include will be
  # added right above the generated item list, if present
  include_content: true
  # if include_analytics is true, the content of the analytics.html include will
  # be added at the end of the <head> section. You can add your Google Analytics
  # Tracking Code to that file.
  include_analytics: false
  # Twitter @username (as defined by the Twitter Card specs)

# exclude
exclude: ["CNAME", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]

# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty
